import { MissionListView, MissionListAdapter } from "./views/mission_list_view.slint";
export { MissionListAdapter }

import { CreateMissionView, CreateMissionAdapter } from "./views/create_mission_view.slint";
export { CreateMissionAdapter }

import { PowerPresetListView, PowerPresetListAdapter } from "./views/power_preset_list_view.slint";
export { PowerPresetListAdapter }

import { CreatePowerPresetView, CreatePowerPresetAdapter } from "./views/create_power_preset_view.slint";
export { CreatePowerPresetAdapter }

import { FrequencyPresetListView, FrequencyPresetListAdapter } from "./views/frequency_preset_list_view.slint";
export { FrequencyPresetListAdapter }

import { CreateFrequencyPresetView, CreateFrequencyPresetAdapter } from "./views/create_frequency_preset_view.slint";
export { CreateFrequencyPresetAdapter }

import { TaskListView, TaskListAdapter } from "./views/task_list_view.slint";
export { TaskListAdapter }

import { CreateTaskView, CreateTaskAdapter } from "./views/create_task_view.slint";
export { CreateTaskAdapter }

import { AnimationSettings } from "./widgets/styling.slint";
import { Tabs } from "tabs.slint";
import { TabWidget } from "std-widgets.slint";
import { Tab1 } from "tab1.slint";

export global NavigationAdapter {
    out property <int> current-page;

    public function next-page() {
        root.current-page += 1;
    }

    public function previous-page() {
        root.current-page = max(0, root.current-page - 1);
    }
}

export global MissionNavigationAdapter {
    out property <int> current-page;
    in-out property <int> current-mission;

    public function next-page() {
        debug("mission next page");
        root.current-page += 1;
    }

    public function previous-page() {
        debug("mission prev page");
        root.current-page = max(0, root.current-page - 1);
    }
}

export global PowerPresetNavigationAdapter {
    out property <int> current-page;
    in-out property <int> current-power-preset;

    public function next-page() {
        root.current-page += 1;
    }

    public function previous-page() {
        root.current-page = max(0, root.current-page - 1);
    }
}

export global FrequencyPresetNavigationAdapter {
    out property <int> current-page;
    in-out property <int> current-frequency-preset;

    public function next-page() {
        debug("frequency preset next page");
        root.current-page += 1;
    }

    public function previous-page() {
        debug("frequency preset prev page");
        root.current-page = max(0, root.current-page - 1);
    }
}

export component MainWindow inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;
    title: "Radio Configuration Tool";
    // Tabs {}
    TabWidget {
        Tab {
            title: "General";
            Tab1 {}
        }
        Tab {
            title: "Missions";
            Rectangle {
                // border-color: yellow;
                // border-width: 10px;
                // padding: 30px;
                x: -(MissionNavigationAdapter.current-page * root.width);
                width: 2 * root.width;

                // if self.x > -root.width : MissionListView {
                if MissionNavigationAdapter.current-page == 0  : MissionListView {
                    x: 0 + 10px;
                    y: 10px;
                    // padding: 20px;
                    width: root.width - 20px;
                    height: root.height - 35px;
                }

                // if self.x < 0 : CreateMissionView {
                if MissionNavigationAdapter.current-page == 1  : CreateMissionView {
                    x: root.width + 20px;
                    y: 10px;
                    width: root.width - 40px;
                    height: root.height - 35px;
                }

                animate x {
                    duration: AnimationSettings.move-duration;
                    easing: AnimationSettings.move-easing;
                }
            }
        }
        Tab {
            title: "Power Presets";
            Rectangle {
                // border-color: yellow;
                // border-width: 10px;
                // padding: 30px;
                x: -(PowerPresetNavigationAdapter.current-page * root.width);
                width: 2 * root.width;

                // if self.x > -root.width : MissionListView {
                if PowerPresetNavigationAdapter.current-page == 0  : PowerPresetListView {
                    x: 0 + 10px;
                    y: 10px;
                    // padding: 20px;
                    width: root.width - 20px;
                    height: root.height - 35px;
                }

                // if self.x < 0 : CreateMissionView {
                if PowerPresetNavigationAdapter.current-page == 1  : CreatePowerPresetView {
                    x: root.width + 20px;
                    y: 10px;
                    width: root.width - 40px;
                    height: root.height - 35px;
                }

                animate x {
                    duration: AnimationSettings.move-duration;
                    easing: AnimationSettings.move-easing;
                }
            }
        }
        Tab {
            title: "Frequency Presets";
            Rectangle {
                // border-color: yellow;
                // border-width: 10px;
                // padding: 30px;
                x: -(FrequencyPresetNavigationAdapter.current-page * root.width);
                width: 2 * root.width;

                // if self.x > -root.width : MissionListView {
                if FrequencyPresetNavigationAdapter.current-page == 0  : FrequencyPresetListView {
                    x: 0 + 10px;
                    y: 10px;
                    // padding: 20px;
                    width: root.width - 20px;
                    height: root.height - 35px;
                }

                // if self.x < 0 : CreateMissionView {
                if FrequencyPresetNavigationAdapter.current-page == 1  : CreateFrequencyPresetView {
                    x: root.width + 20px;
                    y: 10px;
                    width: root.width - 40px;
                    height: root.height - 35px;
                }

                animate x {
                    duration: AnimationSettings.move-duration;
                    easing: AnimationSettings.move-easing;
                }
            }
        }
        Tab {
            title: "Test Tasks";
            Rectangle {
                // border-color: yellow;
                // border-width: 10px;
                // padding: 30px;
                x: -(NavigationAdapter.current-page * root.width);
                width: 2 * root.width;

                // if self.x > -root.width : TaskListView {
                if NavigationAdapter.current-page == 0  : TaskListView {
                    x: 0 + 10px;
                    y: 10px;
                    // padding: 20px;
                    width: root.width - 20px;
                    height: root.height - 35px;
                }

                // if self.x < 0 : CreateTaskView {
                if NavigationAdapter.current-page == 1  : CreateTaskView {
                    x: root.width + 20px;
                    y: 10px;
                    width: root.width - 40px;
                    height: root.height - 35px;
                }

                animate x {
                    duration: AnimationSettings.move-duration;
                    easing: AnimationSettings.move-easing;
                }
            }
        }
    }

}
